name: flutter_reader
description: "Read Epub."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  epubx: ^4.0.0
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.14.10+1
  html: ^0.15.4
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  path: ^1.8.3

flutter:
  uses-material-design: true
